config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :users, except: [:new]


  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'


  root to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 30, maximum: 1000 }
  validates :user_id, presence: true

  paginates_per 5
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_secure_password 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, 
  format: { with: VALID_EMAIL_REGEX }

  before_save { self.email = email.downcase }

  paginates_per 4
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 helper_method :current_user, :logged_in?, :require_user

 def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

def logged_in?
     !!current_user
 end
def require_user
    if !logged_in?
     flash[:danger] = "You must be logged in to perform that action"
     redirect_to root_path
    end
 end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :verify_user, only: [:edit, :update, :destroy]
  def new
    @article = Article.new
  end

  def create

    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end


  def show
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated"
      redirect_to article_path(@article)
    else
      flash[:notice] = "Article was not updated"
      render 'edit'
    end
  end

  def edit
  end

  def index
    @articles = Article.order(created_at: :desc ).page params[:page]
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted"
    redirect_to articles_path
  end

  private

  def verify_user
    if current_user != @article.user
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
  

 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   end

    def create 
      user = User.find_by(email: params[:session][:email].downcase)
      if user  && user.authenticate(params[:session][:password])
       session[:user_id] = user.id
       flash[:success] = "You have logged in"
       redirect_to users_path(@current_user)
      else
       flash.now[:danger] = "There was something wrong with your login information"
       render 'new'
      end
     end
   

  def destroy
      session[:user_id] = nil
      flash[:success] = "You have logged out"
      redirect_to root_path
    
   end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Your account has been successfully create! Please, login!"
      redirect_to login_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.order(:name).page params[:page]
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


 def can_edit?(user)
  logged_in? && current_user == user
 end

end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
  <div class="container">
    <h3 class="display-4">EDIT ARTICLE</h3>
  </div>
  <br>

<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <h3 align="center" class="display-6">ARTICLES</h3>
</div>

<%= render 'shared/articles', obj: @articles%>

<div align="center">
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<% if logged_in? %> 
<h1 align="center">NEW ARTICLE</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>
<%end%>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <% if @article.user %>
 <ul class="listing">
  <div class="row" align="center">
   <div class="col-md-4 col-md-offset-4">
    <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
   </div>
  </div>
 </ul> 
 <% end %>
 <h4 class="center description"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@article.description) %>
<% if can_edit?(@article.user) %>
  <div class="article-actions">
  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
  <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
  <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
  </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "Vynil", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
  
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "ABOUT", about_path %></li>
        <li class="dropdown">
          <ul class="nav navbar-nav">
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
          <li><%= link_to "ARTICLES", articles_path %></li>
          <li class="dropdown">
          <ul class="nav navbar-nav">
          <li><%= link_to "CREATORS", users_path %></li>

          <% if logged_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ACCOUNT<span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><%= link_to "NEW ARTICLE", new_article_path%></li>
          <li><%= link_to "MY PROFILE", user_path(current_user) %></li>
          <li><%= link_to "LOG OUT", logout_path, method: :delete %></li>
          <% end %>
          </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   
    <title>VYNIL</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600&display=swap" rel="stylesheet">
  
  </head>

<body>
    <%= render 'shared/messages' %>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron"> 
  <h2 align="center" class="display-4">Welcome to VYNIL</h1>
  <hr class="my-4">
  <h3 align="center" class="lead"> This is a platform for people who love records! 
  <h3 align="center" class="lead"> Here we write about music, mainly 
  rock from 70's and 80's, but you can write about any genre and decade if you join us!
   Feel free to read ours articles and meet ours content creators!
  </h3>
  </h3>

 
</div>

app/views/pages/index.html.erb
<br>


<div class="jumbotron jumbotron-fluid" style="background-color: #333333">
  <div class="container">
    <h1 class="display-4" style="color: white">WELCOME TO VYNIL</h1>
    <h3 class="lead" style="color: white"></p>All you need is love...And a record player.
  </div>
  <br>
  <% unless logged_in? %>
    <div align="center">
    <small><%= link_to "LOGIN ", login_path, class: "text-muted" %>     
    <small  style="color: white"> or </small><%= link_to " REGISTER NOW", signup_path, class: "text-muted" %></small>
  <% end %>
</div>

app/views/shared/_articles.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <% if can_edit?(article.user) %>
          <div class="article-actions">
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
            <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :username %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :email %>
   </div>
   <div class="col-sm-8">
    <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :password %>
   </div>
   <div class="col-sm-8">
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
   </div>
  </div>  
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit(@user.new_record?  ? "SIGN UP" : "UPDATE ACCOUNT", class: 'btn btn-dark btn-large') %>
   </div>
  </div>
<% end %>
  <div class="col-xs-4 col-xs-offset-2">
  <small align="center"> <%= link_to 'Cancel request and return to articles', articles_path %> </small>
  </div> 
 </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <h3 align="center" class="display-6">CONTENT CREATORS</h3>
</div>
<div align="center">

  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title"><%= link_to user.username, user_path(user) %></li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>

  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<h1 align="center">SIGN UP</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">

</div>
<h4 align="center"><%= @user.username %>'s articles</h4>

<%= render 'shared/articles', obj: @user.articles %>
<div align="center">
</div>